### ISSUE TITLE
Dgraph 1.2.0 release

### ISSUE THREAD

**Issue by brent-williams** [MichaelJCompton/Dgraph-dotnet#13]
Hi Michael any guidance on expected compatibility with [dgraph 1.2](https://github.com/dgraph-io/dgraph/releases/tag/v1.2.0)?  Do you intend to trail dgraph releases closely or more ad-hoc?  Thanks for any pointers.

**Comment by brent-williams** [comment]
Great news from Slack channel 
> We've just taken the .net client internally in Dgraph and will be releasing an officially supported version.

Closing.

**Comment by Cloud33** [comment]
> Great news from Slack channel
> 
> > We've just taken the .net client internally in Dgraph and will be releasing an officially supported version.
> 
> Closing.

Brother, what's the good news? Share it
